/*
 * generated by Xtext
 */
package org.uqbarproject.pseudo.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PseudoUiModule extends org.uqbarproject.pseudo.ui.AbstractPseudoUiModule {
	public PseudoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
