/*
* generated by Xtext
*/
package org.uqbarproject.pseudo.ui.contentassist;

import org.uqbarproject.pseudo.ui.contentassist.AbstractPseudoProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PseudoProposalProvider extends AbstractPseudoProposalProvider {

}
