/*
 * generated by Xtext
 */
package org.uqbarproject.pseudo;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TokensRuntimeModule extends org.uqbarproject.pseudo.AbstractTokensRuntimeModule {

}
