/*
 * generated by Xtext
 */
package org.uqbarproject.pseudo.ui.outline;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.swt.graphics.Image;
import org.eclipse.xtext.ui.IImageHelper;
import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.uqbarproject.pseudo.pseudo.Attribute;
import org.uqbarproject.pseudo.pseudo.Method;
import org.uqbarproject.pseudo.pseudo.Statement;
import org.uqbarproject.pseudo.pseudo.Type;

import com.google.inject.Inject;

/**
 * customization of the default outline structure
 * 
 */
public class PseudoOutlineTreeProvider extends DefaultOutlineTreeProvider {

  @Inject
  private IImageHelper imageHelper;

  
  
  protected Image _image(Attribute e) {
    return imageHelper.getImage("Attribute.gif");
  }

  protected Image _image(Method e) {
    return imageHelper.getImage("Method.gif");
  }

  protected Image _image(Type e) {
    return imageHelper.getImage("Type.gif");
  }
  
  protected Image _image(EObject e) {
    return imageHelper.getImage("Package.gif");
  }

  protected void _createNode(IOutlineNode parentNode, Statement modelElement) {}

}
