/*
* generated by Xtext
*/
package org.uqbarproject.pseudo.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class PseudoOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
